
default_platform(:ios)

fastlane_require 'xcodeproj'
prefix_dir = "./"
build_dir = "./build"
service_credentials_file = "./fastlane/wdxios-serviceCredential.json"
project_name = "Grapevine"
firebase_cli_path = "/usr/local/bin/firebase"
provisioning_dir = "./fastlane"
xcodeproj = "#{prefix_dir}#{project_name}.xcodeproj"
workspace = "#{prefix_dir}#{project_name}.xcworkspace"
devices = ["iPhone 14"]
provisioning_file_name_prefix = ""
provisioning_file_name = ""
app_iden = ""
# =============
before_all do |lane, options|

  if options[:scheme] == "Grapevine"
    version_prefix = "D."
    firebase_app_id = "1:444550039548:ios:4ece8b5b37a1d25dd55479"
    app_iden = "vn.greenstock.app.dev1"
    provisioning_file_name_prefix = "greenstock"
  elsif options[:scheme] == "GrapevinePro"
    version_prefix = "P."
    firebase_app_id = "1:444550039548:ios:4ece8b5b37a1d25dd55479"
    app_iden = "vn.greenstock.app.dev1"
    provisioning_file_name_prefix = "greenstock"
  else
    
  end

  if options[:archive_method] == "app-store"
    provisioning_file_name = "#{provisioning_file_name_prefix}-appstore"
  else
    provisioning_file_name = "#{provisioning_file_name_prefix}-adhoc"
  end
  
  
  ipa_file_name = "#{options[:scheme]}_#{options[:archive_method]}"
  ENV["IPA_FILE_NAME"] = ipa_file_name
  ENV['CURRENT_VERSION'] = options[:version]
  ENV['VERSION_PREFIX'] = version_prefix
  ENV['APP_IDENTIFIER'] = app_iden
  ENV['ACTIVE_SCHEME'] = options[:scheme]
  ENV['ARCHIVE_METHOD'] = options[:archive_method]
  ENV['CERTIFICATE_FILE_PATH'] = "./fastlane/certificate.p12"
  ENV['PROVISIONING_FILE_PATH'] = "#{provisioning_dir}/#{provisioning_file_name}.mobileprovision"
  ENV['TEAM_ID'] = options[:teamid]
  ENV['BUILD_DIRECTORY'] = build_dir
  ENV['PATH_APP_STORE_CONNECT_API_KEY'] = "fastlane/app-store-connect.json"
  ENV['PATH_DSYM'] = "#{build_dir}/#{ipa_file_name}.app.dSYM.zip"
  ENV['PATH_FIREBASE_CLI'] = "#{firebase_cli_path}"
  ENV['PATH_IPA'] = "#{build_dir}/#{ipa_file_name}.ipa"
  ENV['CURRENT_BUILD_NUMBER'] = "1"
  ENV['FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD'] = options[:specific_password]
  ENV['WORKSPACE'] = workspace
  
end

platform :ios do
 desc "Description of what the lane does"
 lane :codesigning do |options|
   create_keychain(
   name: "Learning1Keychain",
   default_keychain: false,
   unlock: true,
   timeout: 3600,
   lock_when_sleeps: true,
   password: "123456"
 )

 install_provisioning_profile(path: ENV['PROVISIONING_FILE_PATH'])

 import_certificate(
     keychain_name: "Learning1Keychain",
     certificate_path: "ENV['CERTIFICATE_FILE_PATH']",
     keychain_password: "123456",
     certificate_password: "123456",
   )

 end

 lane :buildApp do |options|
   gym(
       scheme: ENV['ACTIVE_SCHEME'],
       workspace: ENV['WORKSPACE'],
       export_method: ENV['ARCHIVE_METHOD'],
       output_directory: ENV['BUILD_DIRECTORY'],
       output_name: "#{ENV['IPA_FILE_NAME']}.ipa",
       clean: true
   )

 end
 
 lane :distribute do |options|

       firebase_app_distribution(
           app: "1:444550039548:ios:4ece8b5b37a1d25dd55479",
           testers: "thuanuit96@gmail.com",
           release_notes: "Deploy new version",
           service_credentials_file: "./fastlane/wdxios-serviceCredential.json",
           ipa_path: ENV['PATH_IPA']

       )

   end
   
   lane :upload_to_app_store do
    deliver(
      ipa: "Grapevine.ipa",
      app_identifier: "vn.greenstock.app.dev1",
      username: "thuanuit96@gmail.com",
      password: "Specific Password",
      skip_screenshots: true,
      skip_metadata: true,
      skip_binary_upload: false
      )
  end

end

