
name: iOS CI Example
on: [push]

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.ACCESSTOKEN }}
          expire-in: 0 # Setting this to 0 will delete all artifact
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: CocoaPod Install
        run: pod install
      - name: Provisioning profile
        run: fastlane codesigning scheme:Grapevine archive_method:app-store
      - name: Build
        run: fastlane buildApp scheme:Grapevine archive_method:app-store
      - name: Distribute 
        run: fastlane distribute scheme:Grapevine archive_method:app-store
