
name: iOS CI
on: [push]

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.ACCESSTOKEN }}
          expire-in: 0 # Setting this to 0 will delete all artifact
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: CocoaPod Install
        run:  pod install
      - name: Build and upload app to firebase
        run: cd ios && fastlane archiveFirebaseDistribute scheme:GrapevineDev archive_method:ad-hoc
