
name: iOS CI Example
on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: CocoaPod Install
        run: pod install
      - name: Provisioning profile
        run: fastlane codesigning
      - name: Build
        run: fastlane buildApp scheme:Grapevine archive_method:app-store
      - name: Distribute
        run: fastlane distribute app_id:${{ secrets.APP_ID }}
